Typeset.Deploy.Web/Models/Deploy/AppHarbor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Typeset.Deploy.Web.Models.Deploy
{
    public class AppHarbor
    {
        [Required]
        [Display(Name = "build url")]
        public string BuildUrl { get; set; }
    }
}

Typeset.Deploy.Web/Controllers/DeployController.cs
using System;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;
using Newtonsoft.Json;
using Typeset.Deploy.Domain.GitHub;
using Typeset.Deploy.Web.Models.Deploy;

namespace Typeset.Deploy.Web.Controllers
{
    public class DeployController : Controller
    {
        private IGitHubRepository GitHubRepository { get; set; }

        public DeployController(IGitHubRepository gitHubRepository)
        {
            if (gitHubRepository == null)
            {
                throw new ArgumentNullException("gitHubRepository");
            }

            GitHubRepository = gitHubRepository;
        }

        [HttpGet]
        public ActionResult AppHarbor()
        {
            return View(new AppHarbor());
        }

        [HttpPost]
        public ActionResult AppHarbor(AppHarbor model)
        {
            if (ModelState.IsValid)
            {
                if (TryDeployToAppHarbor(model.BuildUrl))
                {
                    return View("Successful");
                }
                else
                {
                    return View("Unsuccessful");
                }
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Manually()
        {
            return Redirect("https://github.com/typeset/typeset/wiki/deploy");
        }

        protected string GetLatestCommitId()
        {
            var key = "typeset-latest-commit-id";
            var value = HttpRuntime.Cache.Get(key) as string;

            if (string.IsNullOrWhiteSpace(value))
            {
                value = GitHubRepository.GetLatestCommitSha();
                HttpRuntime.Cache.Insert(key, value, null, Cache.NoAbsoluteExpiration, new TimeSpan(1, 0, 0));
            }

            return value;
        }

        protected string GetDownloadUrl()
        {
            var key = "typeset-download-url";
            var value = HttpRuntime.Cache.Get(key) as string;

            if (string.IsNullOrWhiteSpace(value))
            {
                value = GitHubRepository.GetLatestCommitDownloadUrl();
                HttpRuntime.Cache.Insert(key, value, null, Cache.NoAbsoluteExpiration, new TimeSpan(1, 0, 0));
            }

            return value;
        }

        protected bool TryDeployToAppHarbor(string buildUrl)
        {
            var success = false;

            var downloadUrl = GetDownloadUrl();
            var latestCommitHash = GetLatestCommitId();

            using (var client = new HttpClient())
            {
                var json = new
                {
                    branches = new
                    {
                        @default = new
                        {
                            commit_id = latestCommitHash,
                            commit_message = "deployed via typeset-deploy",
                            download_url = downloadUrl,
                        }
                    }
                };

                var content = new StringContent(JsonConvert.SerializeObject(json));
                var response = client.PostAsync(buildUrl, content).Result;
                var responseBody = response.Content.ReadAsStringAsync().Result;
                success = response.StatusCode.Equals(HttpStatusCode.OK) && string.IsNullOrWhiteSpace(responseBody);
            }

            return success;
        }
    }
}

Typeset.Deploy.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Typeset.Deploy.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Typeset.Deploy.Web/Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Typeset.Deploy.Web.Controllers
{
    public class ValuesController : ApiController
    {
        // GET api/values
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/values/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/values
        public void Post(string value)
        {
        }

        // PUT api/values/5
        public void Put(int id, string value)
        {
        }

        // DELETE api/values/5
        public void Delete(int id)
        {
        }
    }
}

Typeset.Deploy.Web/Views/Deploy/AppHarbor.cshtml
@model Typeset.Deploy.Web.Models.Deploy.AppHarbor
<div class="row">
    <div class="span12">

        <div class="page-header">
            <h1>Deploy to AppHarbor</h1>
        </div>

        @if (!ViewData.ModelState.IsValid)
        {
        <div class="row">
            <div class="span12">
                <div class="alert alert-error">
                    <button class="close" data-dismiss="alert">×</button>
                    <h4 class="alert-heading">Error</h4>
                    @Html.ValidationSummary()
                </div>
            </div>
        </div>
        } 

        <div class="row">
            <div class="span12">
                <form class="well" method="post" action="@Url.Action("AppHarbor", "Deploy")">
                    <label>Build Url</label>
                    <input id="BuildUrl" name="BuildUrl" type="text" class="span4" placeholder="Type something…">
                    <span class="help-block"><a data-toggle="modal" href="#buildUrlHelpModal">Help!</a> I don't know what my build url is.</span>
                    <hr />
                    <button type="submit" class="btn btn-primary">Deploy!</button>
                </form>
            </div>
        </div>
        

        <div class="modal hide" id="buildUrlHelpModal">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h3>Getting your AppHarbor Build Url</h3>
            </div>
            <div class="modal-body">
                <img src="~/content/images/appharbor_build_url.png" />
            </div>
            <div class="modal-footer">
                <a href="#" class="btn" data-dismiss="modal">Close</a>
            </div>
        </div>

    </div>
</div>

Typeset.Deploy.Web/Views/Deploy/Success.cshtml
<div class="row">
    <div class="span12">

        <div class="hero-unit">
            <h1>Success!</h1>
            <p>Typeset has been successfully deployed to your platform provider!</p>
            <p>
                <a class="btn btn-primary btn-large" href="@Url.Action("Index", "Home")">Home</a>
            </p>
        </div>

    </div>
</div>

Typeset.Deploy.Web/Views/Deploy/Successful.cshtml
<div class="row">
    <div class="span12">

        <div class="hero-unit">
            <h1>Success!</h1>
            <p>Typeset has been successfully deployed to your platform provider!</p>
            <p>
                <a class="btn btn-primary btn-large" href="@Url.Action("Index", "Home")">Home</a>
            </p>
        </div>

    </div>
</div>

Typeset.Deploy.Web/Views/Deploy/Unsuccessful.cshtml
<div class="row">
    <div class="span12">

        <div class="hero-unit">
            <h1>Unsuccessful!</h1>
            <p>Typeset was unable to deploy to your platform provider!</p>
            <p>
                <a class="btn btn-primary btn-large" href="@Url.Action("Index", "Home")">Home</a>
            </p>
        </div>

    </div>
</div>

Typeset.Deploy.Web/Views/Home/Index.cshtml
<div class="row">
    <div class="span12">
        <ul class="thumbnails platforms">
          <li class="span4">
            <div class="thumbnail">
                <a href="@Url.Action("AppHarbor", "Deploy")">
                    <img src="~/content/images/appharbor_logo.png" alt="AppHarbor" />
                </a>
                <div class="caption">
                    <h5>AppHarbor</h5>
                    <p>AppHarbor is a fully hosted .NET Platform as a Service. AppHarbor can deploy and scale any standard .NET application to the cloud.</p>
                    <p><a href="@Url.Action("AppHarbor", "Deploy")" class="btn btn-primary"><i class="icon-share icon-white"></i> Deploy to AppHarbor</a></p>
                </div>
            </div>
          </li>
          <li class="span4">
            <div class="thumbnail">
                <a href="https://github.com/typeset/typeset-deploy-web">
                    <img src="~/content/images/octocat.png" alt="GitHub" />
                </a>
                <div class="caption">
                    <h5>GitHub</h5>
                    <p>Don't see your favorite platform here? Typeset Deploy is on GitHub, and we accept contributions.</p>
                    <p><a href="https://github.com/typeset/typeset-deploy-web" class="btn btn-primary"><i class="icon-share icon-white"></i> Fork us on GitHub</a></p>
                </div>
            </div>
          </li>
          <li class="span4">
            <div class="thumbnail">
                <a href="@Url.Action("Manually", "Deploy")">
                    <img src="http://placehold.it/512x512/ffffff&text=manually" alt="manually" />
                </a>
                <div class="caption">
                    <h5>Manually</h5>
                    <p>Prefer to deploy Typeset manually? Sure, no problem. We have documentation for that.</p>
                    <p><a href="@Url.Action("Manually", "Deploy")" class="btn btn-primary"><i class="icon-share icon-white"></i> Deploy Typeset manually</a></p>
                </div>
            </div>
          </li>
        </ul>
    </div>
</div>

Typeset.Deploy.Web/Views/Shared/Analytics.cshtml
<script type="text/javascript">
    var _gauges = _gauges || [];
    (function () {
        var t = document.createElement('script');
        t.type = 'text/javascript';
        t.async = true;
        t.id = 'gauges-tracker';
        t.setAttribute('data-site-id', '50244c0f613f5d0a73000049');
        t.src = '//secure.gaug.es/track.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(t, s);
    })();
</script>

Typeset.Deploy.Web/Views/Shared/Footer.cshtml
<footer>
    <div class="container">
        <div class="row-fluid">
            <div class="span12">
                <ul class="quick-links">
                    <li><a href="https://github.com/typeset/typeset-deploy-web">About</a></li>
                    <li><a href="https://github.com/typeset/typeset-deploy-web/wiki">Documentation</a></li>
                    <li><a href="https://github.com/typeset/typeset-deploy-web/issues">Submit issues</a></li>
                    <li><a href="https://github.com/typeset/typeset-deploy-web">License</a></li>
                </ul>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <ul class="quick-links">
                    <li><a href="https://twitter.com/intent/tweet?button_hashtag=typeset" class="twitter-hashtag-button">Tweet #typeset</a></li>
                    <li><iframe src="http://ghbtns.com/github-btn.html?user=typeset&repo=typeset-deploy-web&type=follow&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="150px" height="20px"></iframe></li>
                    <li><iframe src="http://ghbtns.com/github-btn.html?user=typeset&repo=typeset-deploy-web&type=watch&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="95px" height="20px"></iframe></li>
                    <li><iframe src="http://ghbtns.com/github-btn.html?user=typeset&repo=typeset-deploy-web&type=fork&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="95px" height="20px"></iframe></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

Typeset.Deploy.Web/Views/Shared/Header.cshtml
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="~/">Typeset Deploy</a>
            <div class="nav-collapse">
                <ul class="nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-share icon-white"></i> Deploy <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="nav-header">Deploy to..</li>
                            <li>
                                <a href="@Url.Action("AppHarbor", "Deploy")">
                                    <span class="hidden-desktop"><i class="icon-share icon-white"></i> to AppHarbor</span>
                                    <span class="visible-desktop"><i class="icon-share"></i> AppHarbor</span>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="@Url.Action("Manually", "Deploy")">
                                    <span class="hidden-desktop"><i class="icon-share icon-white"></i> Manually</span>
                                    <span class="visible-desktop"><i class="icon-share"></i> Manually</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

Typeset.Deploy.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Deploy Typeset to your favorite platform">
    <meta name="author" content="Bates Westmoreland">
    <meta name="version" content="@Html.ApplicationVersion()">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/content/css")
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    @*<link rel="shortcut icon" href="favicon.ico">*@
</head>
<body>
    @Html.Partial("Header")
    <div class="container">
        @RenderBody()
    </div>
    @Html.Partial("Footer")
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    @Scripts.Render("~/scripts/js/all")
    <script src="https://platform.twitter.com/widgets.js"></script>
    @Html.Partial("Analytics")
</body>
</html>